repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest version
    hooks:
    -   id: black
        language_version: python3.8  # Adjust to your Python version

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1  # Use the latest version
    hooks:
    -   id: isort

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1  # Use the latest version
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.4.0  # Use the latest version
    hooks:
    -   id: eslint
        additional_dependencies: ['eslint@8.4.0', 'eslint-config-airbnb', 'eslint-plugin-import', 'eslint-plugin-jsx-a11y', 'eslint-plugin-react', 'eslint-plugin-react-hooks']
        files: \.(js|jsx)$
        args:
        - --config
        - .eslintrc.json  # Adjust to your ESLint config file
