openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /api/arcs/:
    get:
      operationId: api_arcs_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Arc'
          description: ''
    post:
      operationId: api_arcs_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Arc'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Arc'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Arc'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Arc'
          description: ''
  /api/arcs/{id}/:
    get:
      operationId: api_arcs_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this arc.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Arc'
          description: ''
    put:
      operationId: api_arcs_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this arc.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Arc'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Arc'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Arc'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Arc'
          description: ''
    patch:
      operationId: api_arcs_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this arc.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedArc'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedArc'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedArc'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Arc'
          description: ''
    delete:
      operationId: api_arcs_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this arc.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/demand-nodes/:
    get:
      operationId: api_demand_nodes_list
      description: Abstract base viewset for node-like models with UUID validation.
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DemandNode'
          description: ''
    post:
      operationId: api_demand_nodes_create
      description: Abstract base viewset for node-like models with UUID validation.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemandNode'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DemandNode'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DemandNode'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemandNode'
          description: ''
  /api/demand-nodes/{id}/:
    get:
      operationId: api_demand_nodes_retrieve
      description: Abstract base viewset for node-like models with UUID validation.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this demand node.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemandNode'
          description: ''
    put:
      operationId: api_demand_nodes_update
      description: Abstract base viewset for node-like models with UUID validation.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this demand node.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemandNode'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DemandNode'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DemandNode'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemandNode'
          description: ''
    patch:
      operationId: api_demand_nodes_partial_update
      description: Abstract base viewset for node-like models with UUID validation.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this demand node.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedDemandNode'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedDemandNode'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedDemandNode'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemandNode'
          description: ''
    delete:
      operationId: api_demand_nodes_destroy
      description: Abstract base viewset for node-like models with UUID validation.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this demand node.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/solve/:
    post:
      operationId: api_solve_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Network'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Network'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Network'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Network'
          description: ''
  /api/supply-nodes/:
    get:
      operationId: api_supply_nodes_list
      description: Abstract base viewset for node-like models with UUID validation.
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupplyNode'
          description: ''
    post:
      operationId: api_supply_nodes_create
      description: Abstract base viewset for node-like models with UUID validation.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplyNode'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SupplyNode'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SupplyNode'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplyNode'
          description: ''
  /api/supply-nodes/{id}/:
    get:
      operationId: api_supply_nodes_retrieve
      description: Abstract base viewset for node-like models with UUID validation.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this supply node.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplyNode'
          description: ''
    put:
      operationId: api_supply_nodes_update
      description: Abstract base viewset for node-like models with UUID validation.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this supply node.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplyNode'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SupplyNode'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SupplyNode'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplyNode'
          description: ''
    patch:
      operationId: api_supply_nodes_partial_update
      description: Abstract base viewset for node-like models with UUID validation.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this supply node.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSupplyNode'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSupplyNode'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSupplyNode'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplyNode'
          description: ''
    delete:
      operationId: api_supply_nodes_destroy
      description: Abstract base viewset for node-like models with UUID validation.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this supply node.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Arc:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        start_node:
          type: string
          format: uuid
        end_node:
          type: string
          format: uuid
        cost:
          type: number
          format: double
      required:
      - cost
      - end_node
      - id
      - start_node
    DemandNode:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        node_name:
          type: string
          nullable: true
          maxLength: 100
        demand_amount:
          type: number
          format: double
      required:
      - id
    Network:
      type: object
      properties:
        supply_nodes:
          type: array
          items:
            $ref: '#/components/schemas/SupplyNode'
        demand_nodes:
          type: array
          items:
            $ref: '#/components/schemas/DemandNode'
        arcs:
          type: array
          items:
            $ref: '#/components/schemas/Arc'
      required:
      - arcs
      - demand_nodes
      - supply_nodes
    PatchedArc:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        start_node:
          type: string
          format: uuid
        end_node:
          type: string
          format: uuid
        cost:
          type: number
          format: double
    PatchedDemandNode:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        node_name:
          type: string
          nullable: true
          maxLength: 100
        demand_amount:
          type: number
          format: double
    PatchedSupplyNode:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        node_name:
          type: string
          nullable: true
          maxLength: 100
        supply_amount:
          type: number
          format: double
    SupplyNode:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        node_name:
          type: string
          nullable: true
          maxLength: 100
        supply_amount:
          type: number
          format: double
      required:
      - id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
