# Generated by Django 4.2.7 on 2023-12-27 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandNode',
            fields=[
                ('basenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netflow_app.basenode')),
                ('demand_amount', models.FloatField(default=0)),
            ],
            bases=('netflow_app.basenode',),
        ),
        migrations.CreateModel(
            name='SupplyNode',
            fields=[
                ('basenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netflow_app.basenode')),
                ('supply_amount', models.FloatField(default=0)),
            ],
            bases=('netflow_app.basenode',),
        ),
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_arcs', to='netflow_app.basenode')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_arcs', to='netflow_app.basenode')),
            ],
        ),
    ]
