# Generated by Django 4.2.7 on 2024-01-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflow_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='capacity',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='arc',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
