# Generated by Django 4.2.2 on 2023-06-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netflow_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="type",
            field=models.CharField(
                choices=[
                    ("supply", "Supply"),
                    ("demand", "Demand"),
                    ("storage", "Storage"),
                ],
                max_length=76,
            ),
        ),
    ]
