# Generated by Django 4.2.7 on 2023-12-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflow_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageNode',
            fields=[
                ('basenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netflow_app.basenode')),
                ('capacity', models.FloatField(default=0)),
                ('initial_amount', models.FloatField(default=0)),
            ],
            bases=('netflow_app.basenode',),
        ),
    ]
