# Generated by Django 4.2.7 on 2024-01-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflow_app', '0002_arc_capacity_alter_arc_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesteps', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='arc_flows',
            new_name='timestep_arc_flows',
        ),
    ]
