# Generated by Django 4.2.2 on 2023-06-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netflow_app", "0002_node_name_alter_node_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="node",
            old_name="name",
            new_name="node_name",
        ),
    ]
