# Generated by Django 4.2.7 on 2024-01-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflow_app', '0003_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
