# Generated by Django 4.2.2 on 2023-06-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("netflow_app", "0003_rename_name_node_node_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "end_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_arcs",
                        to="netflow_app.node",
                    ),
                ),
                (
                    "start_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_arcs",
                        to="netflow_app.node",
                    ),
                ),
            ],
        ),
    ]
