# Generated by Django 4.2.7 on 2023-12-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflow_app', '0005_remove_node_x_remove_node_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
