# Generated by Django 4.2.7 on 2023-12-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflow_app', '0006_arc_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=100, null=True)),
                ('demand_amount', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_amount', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
