# Generated by Django 4.2.7 on 2023-12-20 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('netflow_app', '0007_demandnode_supplynode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandnode',
            name='demand_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='demandnode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplynode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplynode',
            name='supply_amount',
            field=models.FloatField(default=0),
        ),
    ]
